services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: project_management_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql # Aqui você referencia o volume
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-ppassword"]
      timeout: 5s
      retries: 10
      interval: 5s

  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URI: mysql+pymysql://user:password@db/project_management_db
      FLASK_APP: app.py
      FLASK_ENV: development
    command: >
      sh -c "flask db upgrade &&
             flask run --host=0.0.0.0"

# --- Definição dos volumes ---
volumes: # Adicione esta seção
  db_data: # Declare o volume nomeado aqui